export const SET_HOME_DATA = 'SET_HOME_DATA'

export const SET_SHOP_DATA = 'SET_SHOP_DATA'

export const SET_USERINFO_DATA = 'SET_USERINFO_DATA'

export const SET_USERADDRESSLIST_DATA = 'SET_USERADDRESSLIST_DATA'

export const SET_USERADDRESS_DATA = 'SET_USERADDRESS_DATA'

export const SET_BANNER_DATA = 'SET_BANNER_DATA'

export const SET_SELECTED_DATA = 'SET_SELECTED_DATA'

export const SET_CONFIG_DATA = 'SET_CONFIG_DATA'

export const SET_CONFIGWEB_DATA = 'SET_CONFIGWEB_DATA'