export const SET_HOME_DATA = 'SET_HOME_DATA'

export const SET_USERINFO_DATA = 'SET_USERINFO_DATA'

export const SET_APP_DATA = 'SET_APP_DATA'

export const SET_SELECTED_DATA = 'SET_SELECTED_DATA'

export const SET_USERADDRESSLIST_DATA = 'SET_USERADDRESSLIST_DATA'